### ISSUE TITLE
Bug: Failed import of tags containing certain special characters

### ISSUE THREAD

**Issue by admbeck** [resucutie/localbooru#15]
**Describe the bug**
Tags are not automatically imported if they contain certain special characters like `<`. Other symbols untested.

**To Reproduce**
1. Click Import from service
2. Paste a link to an image that contains `<` in its tags on website, [example](https://gelbooru.com/index.php?page=post&s=view&id=9380747&tags=yihan1949)
3. See the following in the tags: `1girl :`

**Expected behavior**
Tags to be imported as they do with other images

**Screenshots**
Tags on gelbooru:
![image](https://github.com/user-attachments/assets/915f756f-704d-43a9-855f-bdc9ca05f637)

Imported tags
![image](https://github.com/user-attachments/assets/b68500e4-43f9-4ff1-a46a-4adeb9fa9b8e)

**System informations:**
 - Device: Desktop
 - OS: Arch Linux
 - Package: Binary
 - Version: 1.5.2

**Comment by resucutie** [comment]
Gelbooru I love you

Apparently Gelbooru [converts `>` into `&lt;`](https://gelbooru.com/index.php?page=dapi&s=post&q=index&json=1&id=9380747#:~:text=178%2C%22tags%22%3A%221girl-,%3A%26lt%3B,-absurdres%20animal_ears%20brown_eyes), for, some.... reason. Probably PHP hell  
Either way, after some debugging, when finding for tag types (you have to do a different request to obtain that information), gelbooru cannot find the tag `:&lt;`, but it can find `:<` and will return this about:
```json
{
      "id": 45162,
      "name": ":&lt;",
      "count": 36894,
      "type": 0,
      "ambiguous": 0
},
```
So the fix is to parse the tags before sending

**Comment by resucutie** [comment]
Apparently the only future proof option that I have is [using this old ass package](https://pub.dev/packages/html_unescape), because there is no built-in html unescaper for dart, [even tho an html escaper is literally built in](https://api.dart.dev/stable/3.5.1/dart-convert/HtmlEscape-class.html)

More stupid dependencies wooooooo
