### ISSUE TITLE
Application closes when opening .exe

### ISSUE THREAD

**Issue by DearFox** [resucutie/localbooru#28]
**Describe the bug**
When you open an exe file, a program window appears and disappears after a few seconds.

**To Reproduce**
1. download localbooru-windows-portable.zip
2. Extract to `D:\.localbooru\app`
3. Run localbooru.exe
4. ![img](https://github.com/user-attachments/assets/6ea33ca5-e2a8-4aaa-a0e9-558eab5e69c4)

**Expected behavior**
Starting the program

**Screenshots**

**System informations:**
 - Device: PC
 - OS: Windows 10
 - Package: windows portable
 - Version 1.6.0-prerelease1

**Comment by resucutie** [comment]
Tested with 1.5.2. Seems to work over there

**Comment by resucutie** [comment]
manually decided to build it. apparently the release version does not open but debug does?

**Comment by resucutie** [comment]
Found the issue: it is media_kit being stable as it is

Apparently MediaKit.ensureInitialized() just hangs out on Windows when building for release. That explains a lot due to its optimizations that are done on release but not in debug
![image](https://github.com/user-attachments/assets/18b6f9d7-f52d-428b-9e74-05c089e750e0)

**Comment by resucutie** [comment]
so, i've switched to fvp. it is playing videos over on windows, but on linux it crashes when trying to play

also look, zero crashes on windows! and video playback!
![image](https://github.com/user-attachments/assets/c558a437-a12c-45a0-90f7-006a30e3e7aa)

**Comment by resucutie** [comment]
#31 merged onto dev branch
